### ISSUE TITLE
Rider recent projects are not found

### ISSUE THREAD

**Issue by axelgenus** [lunaryorn/gnome-search-providers-jetbrains#12]
There is a structural difference between Rider's and other Jetbrains IDE's recent projects/solutions XML file.

I changed line 49 from:

`.find(|e| e.get_attr("name") == Some("RecentProjectsManager"))`

to

`.find(|e| e.get_attr("name") == Some("RecentProjectsManager") || e.get_attr("name") == Some("RiderRecentProjectsManager"))`

and it worked.

Probably there is a more elegant way to handle it (a `contains` of `endsWith` methods) but I am not really proficient with Rust.

**Comment by lunaryorn** [comment]
Please do make a pull request 🙂

**Comment by lunaryorn** [comment]
@axelgenus I've published 1.4.1 with this fix.
